// Generated by gencpp from file cs476/FloatArray.msg
// DO NOT EDIT!


#ifndef CS476_MESSAGE_FLOATARRAY_H
#define CS476_MESSAGE_FLOATARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cs476
{
template <class ContainerAllocator>
struct FloatArray_
{
  typedef FloatArray_<ContainerAllocator> Type;

  FloatArray_()
    : nums()  {
    }
  FloatArray_(const ContainerAllocator& _alloc)
    : nums(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _nums_type;
  _nums_type nums;





  typedef boost::shared_ptr< ::cs476::FloatArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cs476::FloatArray_<ContainerAllocator> const> ConstPtr;

}; // struct FloatArray_

typedef ::cs476::FloatArray_<std::allocator<void> > FloatArray;

typedef boost::shared_ptr< ::cs476::FloatArray > FloatArrayPtr;
typedef boost::shared_ptr< ::cs476::FloatArray const> FloatArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cs476::FloatArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cs476::FloatArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cs476::FloatArray_<ContainerAllocator1> & lhs, const ::cs476::FloatArray_<ContainerAllocator2> & rhs)
{
  return lhs.nums == rhs.nums;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cs476::FloatArray_<ContainerAllocator1> & lhs, const ::cs476::FloatArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cs476

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cs476::FloatArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cs476::FloatArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cs476::FloatArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cs476::FloatArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs476::FloatArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cs476::FloatArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cs476::FloatArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a327f765b70d8bd267a8d96beb763ec";
  }

  static const char* value(const ::cs476::FloatArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a327f765b70d8bdULL;
  static const uint64_t static_value2 = 0x267a8d96beb763ecULL;
};

template<class ContainerAllocator>
struct DataType< ::cs476::FloatArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cs476/FloatArray";
  }

  static const char* value(const ::cs476::FloatArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cs476::FloatArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] nums\n"
;
  }

  static const char* value(const ::cs476::FloatArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cs476::FloatArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nums);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FloatArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cs476::FloatArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cs476::FloatArray_<ContainerAllocator>& v)
  {
    s << indent << "nums[]" << std::endl;
    for (size_t i = 0; i < v.nums.size(); ++i)
    {
      s << indent << "  nums[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.nums[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CS476_MESSAGE_FLOATARRAY_H
