// Generated by gencpp from file FinalProject/Path.msg
// DO NOT EDIT!


#ifndef FINALPROJECT_MESSAGE_PATH_H
#define FINALPROJECT_MESSAGE_PATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <FinalProject/Point.h>

namespace FinalProject
{
template <class ContainerAllocator>
struct Path_
{
  typedef Path_<ContainerAllocator> Type;

  Path_()
    : path()  {
    }
  Path_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::FinalProject::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::FinalProject::Point_<ContainerAllocator> >> _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::FinalProject::Path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::FinalProject::Path_<ContainerAllocator> const> ConstPtr;

}; // struct Path_

typedef ::FinalProject::Path_<std::allocator<void> > Path;

typedef boost::shared_ptr< ::FinalProject::Path > PathPtr;
typedef boost::shared_ptr< ::FinalProject::Path const> PathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::FinalProject::Path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::FinalProject::Path_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::FinalProject::Path_<ContainerAllocator1> & lhs, const ::FinalProject::Path_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::FinalProject::Path_<ContainerAllocator1> & lhs, const ::FinalProject::Path_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace FinalProject

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::FinalProject::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::FinalProject::Path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::FinalProject::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::FinalProject::Path_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::FinalProject::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::FinalProject::Path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::FinalProject::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b880b1651666aa52142c963a6ef3debf";
  }

  static const char* value(const ::FinalProject::Path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb880b1651666aa52ULL;
  static const uint64_t static_value2 = 0x142c963a6ef3debfULL;
};

template<class ContainerAllocator>
struct DataType< ::FinalProject::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "FinalProject/Path";
  }

  static const char* value(const ::FinalProject::Path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::FinalProject::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point[] path\n"
"================================================================================\n"
"MSG: FinalProject/Point\n"
"float32 x\n"
"float32 y\n"
"float32 theta\n"
;
  }

  static const char* value(const ::FinalProject::Path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::FinalProject::Path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::FinalProject::Path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::FinalProject::Path_<ContainerAllocator>& v)
  {
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::FinalProject::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FINALPROJECT_MESSAGE_PATH_H
